package fr.robie.messageflow.api;

import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.function.Function;
import java.util.function.Supplier;

/**
 * Sealed interface representing different types of placeholder values.
 *
 * <p>Placeholders can be:
 * <ul>
 *   <li>{@link StaticValue} - Fixed string value</li>
 *   <li>{@link DynamicValue} - Supplier that generates a value at resolution time</li>
 *   <li>{@link PlayerValue} - Function that generates a value based on a Player context</li>
 * </ul>
 *
 * <p>Usage is typically internal; use {@link fr.robie.messageflow.formatter.Placeholder}
 * or {@link GlobalPlaceholderRegistry} to create and manage placeholder values.
 */
public sealed interface PlaceholderValue permits PlaceholderValue.StaticValue, PlaceholderValue.DynamicValue, PlaceholderValue.PlayerValue {

    /**
     * Evaluates this placeholder value.
     *
     * @param player the player context, may be null for non-player-specific values
     * @return the evaluated string value, never null
     * @throws Exception if evaluation fails
     */
    @NotNull String evaluate(@Nullable Player player) throws Exception;

    /**
     * A static placeholder value with a fixed string.
     *
     * @param value the static string value (never null)
     */
    record StaticValue(@NotNull String value) implements PlaceholderValue {

        public StaticValue(@NotNull String value) {
            this.value = value != null ? value : "";
        }

        @Override
        public @NotNull String evaluate(@Nullable Player player) {
            return this.value;
        }
    }

    /**
     * A dynamic placeholder value generated by a supplier.
     * No player context required; evaluated the same way for all players.
     *
     * @param supplier the supplier that generates the string value
     */
    record DynamicValue(@NotNull Supplier<String> supplier) implements PlaceholderValue {

        @Override
        public @NotNull String evaluate(@Nullable Player player) throws Exception {
            String result = this.supplier.get();
            return result != null ? result : "";
        }
    }

    /**
     * A player-specific placeholder value generated by a function.
     * The value depends on the provided Player context.
     *
     * @param function the function that generates the string value based on a player
     */
    record PlayerValue(@NotNull Function<Player, String> function) implements PlaceholderValue {

        @Override
        public @NotNull String evaluate(@Nullable Player player) throws Exception {
            if (player == null) {
                return "";
            }
            String result = this.function.apply(player);
            return result != null ? result : "";
        }
    }

    /**
     * Creates a static placeholder value.
     *
     * @param value the static string value
     * @return a new StaticValue
     */
    static @NotNull PlaceholderValue ofStatic(@NotNull String value) {
        return new StaticValue(value);
    }

    /**
     * Creates a dynamic placeholder value.
     *
     * @param supplier the supplier function
     * @return a new DynamicValue
     */
    static @NotNull PlaceholderValue ofDynamic(@NotNull Supplier<String> supplier) {
        return new DynamicValue(supplier);
    }

    /**
     * Creates a player-specific placeholder value.
     *
     * @param function the player function
     * @return a new PlayerValue
     */
    static @NotNull PlaceholderValue ofPlayer(@NotNull Function<Player, String> function) {
        return new PlayerValue(function);
    }
}
